version: '2'
services:

  # The Application
  dev:
    image: node
    user: "node"
    working_dir: /home/node/app
    environment: 
        - NODE_ENV=development
    volumes:
      - ./:/home/node/app
    ports:
      - 5000:5000
    command: "npm run build"